### ISSUE TITLE
Possible to make a new release for use with composer?

### ISSUE THREAD

**Issue by ampaze** [sanpii/assetic-bundle#3]
I want to avoid using 

`"sanpi/assetic-bundle": "dev-master@dev",`

in my composer.json.

The last release v2.9.0 does not seem to contain all changes concerning Symfony 4.

Thanks!

**Comment by htvennik** [comment]
Bump @sanpii

**Comment by sanpii** [comment]
Done, sorry for the delay.

**Comment by ampaze** [comment]
Thanks!

**Comment by ampaze** [comment]
Bump @sanpii

**Comment by htvennik** [comment]
New version (v2.10.0) is visible there now, though it displays commit date, which is not very recent.

**Comment by sanpii** [comment]
I have updated the packagist integration. The v2.10.0 is the latest version.

**Comment by ampaze** [comment]
Working now. Thanks.
